// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/chatpb.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WsEventType int32

const (
	WsEventType_EVENT_UNKNOWN   WsEventType = 0
	WsEventType_NEW_MESSAGE     WsEventType = 1
	WsEventType_READ_RECEIPT    WsEventType = 2
	WsEventType_TYPING_START    WsEventType = 3
	WsEventType_TYPING_STOP     WsEventType = 4
	WsEventType_PRESENCE_UPDATE WsEventType = 5
	WsEventType_ORDER_UPDATE    WsEventType = 6
	WsEventType_BOOKING_UPDATE  WsEventType = 7
	WsEventType_UNREAD_COUNT    WsEventType = 8
	WsEventType_PING            WsEventType = 9
	WsEventType_PONG            WsEventType = 10
)

// Enum value maps for WsEventType.
var (
	WsEventType_name = map[int32]string{
		0:  "EVENT_UNKNOWN",
		1:  "NEW_MESSAGE",
		2:  "READ_RECEIPT",
		3:  "TYPING_START",
		4:  "TYPING_STOP",
		5:  "PRESENCE_UPDATE",
		6:  "ORDER_UPDATE",
		7:  "BOOKING_UPDATE",
		8:  "UNREAD_COUNT",
		9:  "PING",
		10: "PONG",
	}
	WsEventType_value = map[string]int32{
		"EVENT_UNKNOWN":   0,
		"NEW_MESSAGE":     1,
		"READ_RECEIPT":    2,
		"TYPING_START":    3,
		"TYPING_STOP":     4,
		"PRESENCE_UPDATE": 5,
		"ORDER_UPDATE":    6,
		"BOOKING_UPDATE":  7,
		"UNREAD_COUNT":    8,
		"PING":            9,
		"PONG":            10,
	}
)

func (x WsEventType) Enum() *WsEventType {
	p := new(WsEventType)
	*p = x
	return p
}

func (x WsEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WsEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chatpb_proto_enumTypes[0].Descriptor()
}

func (WsEventType) Type() protoreflect.EnumType {
	return &file_proto_chatpb_proto_enumTypes[0]
}

func (x WsEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WsEventType.Descriptor instead.
func (WsEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_chatpb_proto_rawDescGZIP(), []int{0}
}

type WsFrame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventType      WsEventType            `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=chatpb.WsEventType" json:"event_type,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderType     string                 `protobuf:"bytes,4,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WsFrame_NewMessage
	//	*WsFrame_ReadReceipt
	//	*WsFrame_Typing
	//	*WsFrame_Presence
	//	*WsFrame_OrderUpdate
	//	*WsFrame_BookingUpdate
	//	*WsFrame_UnreadCount
	Payload       isWsFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsFrame) Reset() {
	*x = WsFrame{}
	mi := &file_proto_chatpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsFrame) ProtoMessage() {}

func (x *WsFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsFrame.ProtoReflect.Descriptor instead.
func (*WsFrame) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_proto_rawDescGZIP(), []int{0}
}

func (x *WsFrame) GetEventType() WsEventType {
	if x != nil {
		return x.EventType
	}
	return WsEventType_EVENT_UNKNOWN
}

func (x *WsFrame) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *WsFrame) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *WsFrame) GetSenderType() string {
	if x != nil {
		return x.SenderType
	}
	return ""
}

func (x *WsFrame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WsFrame) GetPayload() isWsFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WsFrame) GetNewMessage() *NewMessage {
	if x != nil {
		if x, ok := x.Payload.(*WsFrame_NewMessage); ok {
			return x.NewMessage
		}
	}
	return nil
}

func (x *WsFrame) GetReadReceipt() *ReadReceipt {
	if x != nil {
		if x, ok := x.Payload.(*WsFrame_ReadReceipt); ok {
			return x.ReadReceipt
		}
	}
	return nil
}

func (x *WsFrame) GetTyping() *TypingIndicator {
	if x != nil {
		if x, ok := x.Payload.(*WsFrame_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

func (x *WsFrame) GetPresence() *PresenceUpdate {
	if x != nil {
		if x, ok := x.Payload.(*WsFrame_Presence); ok {
			return x.Presence
		}
	}
	return nil
}

func (x *WsFrame) GetOrderUpdate() *OrderUpdate {
	if x != nil {
		if x, ok := x.Payload.(*WsFrame_OrderUpdate); ok {
			return x.OrderUpdate
		}
	}
	return nil
}

func (x *WsFrame) GetBookingUpdate() *BookingUpdate {
	if x != nil {
		if x, ok := x.Payload.(*WsFrame_BookingUpdate); ok {
			return x.BookingUpdate
		}
	}
	return nil
}

func (x *WsFrame) GetUnreadCount() *UnreadCount {
	if x != nil {
		if x, ok := x.Payload.(*WsFrame_UnreadCount); ok {
			return x.UnreadCount
		}
	}
	return nil
}

type isWsFrame_Payload interface {
	isWsFrame_Payload()
}

type WsFrame_NewMessage struct {
	NewMessage *NewMessage `protobuf:"bytes,10,opt,name=new_message,json=newMessage,proto3,oneof"`
}

type WsFrame_ReadReceipt struct {
	ReadReceipt *ReadReceipt `protobuf:"bytes,11,opt,name=read_receipt,json=readReceipt,proto3,oneof"`
}

type WsFrame_Typing struct {
	Typing *TypingIndicator `protobuf:"bytes,12,opt,name=typing,proto3,oneof"`
}

type WsFrame_Presence struct {
	Presence *PresenceUpdate `protobuf:"bytes,13,opt,name=presence,proto3,oneof"`
}

type WsFrame_OrderUpdate struct {
	OrderUpdate *OrderUpdate `protobuf:"bytes,14,opt,name=order_update,json=orderUpdate,proto3,oneof"`
}

type WsFrame_BookingUpdate struct {
	BookingUpdate *BookingUpdate `protobuf:"bytes,15,opt,name=booking_update,json=bookingUpdate,proto3,oneof"`
}

type WsFrame_UnreadCount struct {
	UnreadCount *UnreadCount `protobuf:"bytes,16,opt,name=unread_count,json=unreadCount,proto3,oneof"`
}

func (*WsFrame_NewMessage) isWsFrame_Payload() {}

func (*WsFrame_ReadReceipt) isWsFrame_Payload() {}

func (*WsFrame_Typing) isWsFrame_Payload() {}

func (*WsFrame_Presence) isWsFrame_Payload() {}

func (*WsFrame_OrderUpdate) isWsFrame_Payload() {}

func (*WsFrame_BookingUpdate) isWsFrame_Payload() {}

func (*WsFrame_UnreadCount) isWsFrame_Payload() {}

type NewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,4,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	MediaType     string                 `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	MsgType       string                 `protobuf:"bytes,6,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,8,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessage) Reset() {
	*x = NewMessage{}
	mi := &file_proto_chatpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessage) ProtoMessage() {}

func (x *NewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessage.ProtoReflect.Descriptor instead.
func (*NewMessage) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_proto_rawDescGZIP(), []int{1}
}

func (x *NewMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NewMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *NewMessage) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *NewMessage) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *NewMessage) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *NewMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NewMessage) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type ReadReceipt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ReaderId       string                 `protobuf:"bytes,2,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"`
	ReaderType     string                 `protobuf:"bytes,3,opt,name=reader_type,json=readerType,proto3" json:"reader_type,omitempty"`
	ConversationId string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadReceipt) Reset() {
	*x = ReadReceipt{}
	mi := &file_proto_chatpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceipt) ProtoMessage() {}

func (x *ReadReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceipt.ProtoReflect.Descriptor instead.
func (*ReadReceipt) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_proto_rawDescGZIP(), []int{2}
}

func (x *ReadReceipt) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ReadReceipt) GetReaderId() string {
	if x != nil {
		return x.ReaderId
	}
	return ""
}

func (x *ReadReceipt) GetReaderType() string {
	if x != nil {
		return x.ReaderType
	}
	return ""
}

func (x *ReadReceipt) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type TypingIndicator struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType       string                 `protobuf:"bytes,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ClientId       string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	BusinessId     string                 `protobuf:"bytes,5,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypingIndicator) Reset() {
	*x = TypingIndicator{}
	mi := &file_proto_chatpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingIndicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingIndicator) ProtoMessage() {}

func (x *TypingIndicator) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingIndicator.ProtoReflect.Descriptor instead.
func (*TypingIndicator) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_proto_rawDescGZIP(), []int{3}
}

func (x *TypingIndicator) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TypingIndicator) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *TypingIndicator) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *TypingIndicator) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TypingIndicator) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

type PresenceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	IsOnline      bool                   `protobuf:"varint,2,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	LastSeen      int64                  `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceUpdate) Reset() {
	*x = PresenceUpdate{}
	mi := &file_proto_chatpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceUpdate) ProtoMessage() {}

func (x *PresenceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceUpdate.ProtoReflect.Descriptor instead.
func (*PresenceUpdate) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_proto_rawDescGZIP(), []int{4}
}

func (x *PresenceUpdate) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PresenceUpdate) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *PresenceUpdate) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type OrderUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PaidAmount    float64                `protobuf:"fixed64,3,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PendingAmount float64                `protobuf:"fixed64,5,opt,name=pending_amount,json=pendingAmount,proto3" json:"pending_amount,omitempty"`
	HasReview     bool                   `protobuf:"varint,6,opt,name=has_review,json=hasReview,proto3" json:"has_review,omitempty"`
	ReviewRating  int32                  `protobuf:"varint,7,opt,name=review_rating,json=reviewRating,proto3" json:"review_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdate) Reset() {
	*x = OrderUpdate{}
	mi := &file_proto_chatpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdate) ProtoMessage() {}

func (x *OrderUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdate.ProtoReflect.Descriptor instead.
func (*OrderUpdate) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_proto_rawDescGZIP(), []int{5}
}

func (x *OrderUpdate) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderUpdate) GetPaidAmount() float64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *OrderUpdate) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderUpdate) GetPendingAmount() float64 {
	if x != nil {
		return x.PendingAmount
	}
	return 0
}

func (x *OrderUpdate) GetHasReview() bool {
	if x != nil {
		return x.HasReview
	}
	return false
}

func (x *OrderUpdate) GetReviewRating() int32 {
	if x != nil {
		return x.ReviewRating
	}
	return 0
}

type BookingUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PaidAmount    float64                `protobuf:"fixed64,3,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PendingAmount float64                `protobuf:"fixed64,5,opt,name=pending_amount,json=pendingAmount,proto3" json:"pending_amount,omitempty"`
	HasReview     bool                   `protobuf:"varint,6,opt,name=has_review,json=hasReview,proto3" json:"has_review,omitempty"`
	ReviewRating  int32                  `protobuf:"varint,7,opt,name=review_rating,json=reviewRating,proto3" json:"review_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingUpdate) Reset() {
	*x = BookingUpdate{}
	mi := &file_proto_chatpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingUpdate) ProtoMessage() {}

func (x *BookingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingUpdate.ProtoReflect.Descriptor instead.
func (*BookingUpdate) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_proto_rawDescGZIP(), []int{6}
}

func (x *BookingUpdate) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BookingUpdate) GetPaidAmount() float64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *BookingUpdate) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *BookingUpdate) GetPendingAmount() float64 {
	if x != nil {
		return x.PendingAmount
	}
	return 0
}

func (x *BookingUpdate) GetHasReview() bool {
	if x != nil {
		return x.HasReview
	}
	return false
}

func (x *BookingUpdate) GetReviewRating() int32 {
	if x != nil {
		return x.ReviewRating
	}
	return 0
}

type UnreadCount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Count          int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnreadCount) Reset() {
	*x = UnreadCount{}
	mi := &file_proto_chatpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadCount) ProtoMessage() {}

func (x *UnreadCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadCount.ProtoReflect.Descriptor instead.
func (*UnreadCount) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_proto_rawDescGZIP(), []int{7}
}

func (x *UnreadCount) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UnreadCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_chatpb_proto protoreflect.FileDescriptor

const file_proto_chatpb_proto_rawDesc = "" +
	"\n" +
	"\x12proto/chatpb.proto\x12\x06chatpb\"\xdb\x04\n" +
	"\aWsFrame\x122\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x13.chatpb.WsEventTypeR\teventType\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vsender_type\x18\x04 \x01(\tR\n" +
	"senderType\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x125\n" +
	"\vnew_message\x18\n" +
	" \x01(\v2\x12.chatpb.NewMessageH\x00R\n" +
	"newMessage\x128\n" +
	"\fread_receipt\x18\v \x01(\v2\x13.chatpb.ReadReceiptH\x00R\vreadReceipt\x121\n" +
	"\x06typing\x18\f \x01(\v2\x17.chatpb.TypingIndicatorH\x00R\x06typing\x124\n" +
	"\bpresence\x18\r \x01(\v2\x16.chatpb.PresenceUpdateH\x00R\bpresence\x128\n" +
	"\forder_update\x18\x0e \x01(\v2\x13.chatpb.OrderUpdateH\x00R\vorderUpdate\x12>\n" +
	"\x0ebooking_update\x18\x0f \x01(\v2\x15.chatpb.BookingUpdateH\x00R\rbookingUpdate\x128\n" +
	"\funread_count\x18\x10 \x01(\v2\x13.chatpb.UnreadCountH\x00R\vunreadCountB\t\n" +
	"\apayload\"\xe1\x01\n" +
	"\n" +
	"NewMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1b\n" +
	"\tmedia_url\x18\x04 \x01(\tR\bmediaUrl\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x12\x19\n" +
	"\bmsg_type\x18\x06 \x01(\tR\amsgType\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tdata_json\x18\b \x01(\fR\bdataJson\"\x93\x01\n" +
	"\vReadReceipt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\treader_id\x18\x02 \x01(\tR\breaderId\x12\x1f\n" +
	"\vreader_type\x18\x03 \x01(\tR\n" +
	"readerType\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\"\xae\x01\n" +
	"\x0fTypingIndicator\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_type\x18\x02 \x01(\tR\buserType\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x1f\n" +
	"\vbusiness_id\x18\x05 \x01(\tR\n" +
	"businessId\"g\n" +
	"\x0ePresenceUpdate\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tis_online\x18\x02 \x01(\bR\bisOnline\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\"\xef\x01\n" +
	"\vOrderUpdate\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vpaid_amount\x18\x03 \x01(\x01R\n" +
	"paidAmount\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12%\n" +
	"\x0epending_amount\x18\x05 \x01(\x01R\rpendingAmount\x12\x1d\n" +
	"\n" +
	"has_review\x18\x06 \x01(\bR\thasReview\x12#\n" +
	"\rreview_rating\x18\a \x01(\x05R\freviewRating\"\xf5\x01\n" +
	"\rBookingUpdate\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vpaid_amount\x18\x03 \x01(\x01R\n" +
	"paidAmount\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12%\n" +
	"\x0epending_amount\x18\x05 \x01(\x01R\rpendingAmount\x12\x1d\n" +
	"\n" +
	"has_review\x18\x06 \x01(\bR\thasReview\x12#\n" +
	"\rreview_rating\x18\a \x01(\x05R\freviewRating\"L\n" +
	"\vUnreadCount\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count*\xc7\x01\n" +
	"\vWsEventType\x12\x11\n" +
	"\rEVENT_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vNEW_MESSAGE\x10\x01\x12\x10\n" +
	"\fREAD_RECEIPT\x10\x02\x12\x10\n" +
	"\fTYPING_START\x10\x03\x12\x0f\n" +
	"\vTYPING_STOP\x10\x04\x12\x13\n" +
	"\x0fPRESENCE_UPDATE\x10\x05\x12\x10\n" +
	"\fORDER_UPDATE\x10\x06\x12\x12\n" +
	"\x0eBOOKING_UPDATE\x10\a\x12\x10\n" +
	"\fUNREAD_COUNT\x10\b\x12\b\n" +
	"\x04PING\x10\t\x12\b\n" +
	"\x04PONG\x10\n" +
	"B\x1aZ\x18salesmee/internal/chatpbb\x06proto3"

var (
	file_proto_chatpb_proto_rawDescOnce sync.Once
	file_proto_chatpb_proto_rawDescData []byte
)

func file_proto_chatpb_proto_rawDescGZIP() []byte {
	file_proto_chatpb_proto_rawDescOnce.Do(func() {
		file_proto_chatpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chatpb_proto_rawDesc), len(file_proto_chatpb_proto_rawDesc)))
	})
	return file_proto_chatpb_proto_rawDescData
}

var file_proto_chatpb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_chatpb_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_chatpb_proto_goTypes = []any{
	(WsEventType)(0),        // 0: chatpb.WsEventType
	(*WsFrame)(nil),         // 1: chatpb.WsFrame
	(*NewMessage)(nil),      // 2: chatpb.NewMessage
	(*ReadReceipt)(nil),     // 3: chatpb.ReadReceipt
	(*TypingIndicator)(nil), // 4: chatpb.TypingIndicator
	(*PresenceUpdate)(nil),  // 5: chatpb.PresenceUpdate
	(*OrderUpdate)(nil),     // 6: chatpb.OrderUpdate
	(*BookingUpdate)(nil),   // 7: chatpb.BookingUpdate
	(*UnreadCount)(nil),     // 8: chatpb.UnreadCount
}
var file_proto_chatpb_proto_depIdxs = []int32{
	0, // 0: chatpb.WsFrame.event_type:type_name -> chatpb.WsEventType
	2, // 1: chatpb.WsFrame.new_message:type_name -> chatpb.NewMessage
	3, // 2: chatpb.WsFrame.read_receipt:type_name -> chatpb.ReadReceipt
	4, // 3: chatpb.WsFrame.typing:type_name -> chatpb.TypingIndicator
	5, // 4: chatpb.WsFrame.presence:type_name -> chatpb.PresenceUpdate
	6, // 5: chatpb.WsFrame.order_update:type_name -> chatpb.OrderUpdate
	7, // 6: chatpb.WsFrame.booking_update:type_name -> chatpb.BookingUpdate
	8, // 7: chatpb.WsFrame.unread_count:type_name -> chatpb.UnreadCount
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_chatpb_proto_init() }
func file_proto_chatpb_proto_init() {
	if File_proto_chatpb_proto != nil {
		return
	}
	file_proto_chatpb_proto_msgTypes[0].OneofWrappers = []any{
		(*WsFrame_NewMessage)(nil),
		(*WsFrame_ReadReceipt)(nil),
		(*WsFrame_Typing)(nil),
		(*WsFrame_Presence)(nil),
		(*WsFrame_OrderUpdate)(nil),
		(*WsFrame_BookingUpdate)(nil),
		(*WsFrame_UnreadCount)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chatpb_proto_rawDesc), len(file_proto_chatpb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_chatpb_proto_goTypes,
		DependencyIndexes: file_proto_chatpb_proto_depIdxs,
		EnumInfos:         file_proto_chatpb_proto_enumTypes,
		MessageInfos:      file_proto_chatpb_proto_msgTypes,
	}.Build()
	File_proto_chatpb_proto = out.File
	file_proto_chatpb_proto_goTypes = nil
	file_proto_chatpb_proto_depIdxs = nil
}
